//Script to automate landing of the Vacuum Delivery System (VDS) on any celestial body.
function main {
    //createLandingTrajectory(). //Function to calculate a (hopefully) desirable trajectory for landing.
    deOrbit(). //Function to de-orbit the VDS to initiate the landing sequence.
    executeLandingBurn(). //Function to execute the required landing burn.
    executeRoverInsertion(). //Function to safely detach rover from VDS.
    print "P63 completed.".
}
function createLandingTrajectory { //One day I will add capability to land at a specific location/biome.
     
}
function executeLandingTrajectory { //Executes manuever node generated by createLandingTrajectory().

}
function deOrbit {
    stage.
    lock steering to retrograde.
    wait 20.
    //Takes VDS from stable orbit to suborbital landing trajectory
    //Things we need to know: Periapsis of current orbit (how do we know if the periapsis is low enough? maybe there are parameters for "sea" level vs ground level)
    //is there a way to ensre we are landing somewhere safe? (future integration of SCANSAT slope data possible?)
    local deorbit_alt is (ship:geoposition:terrainheight).
    print "Terrain Height below current ship position: " + deorbit_alt.
    print "Distance to ground at current ship position: " + distanceToground().
    until periapsis <= ship:geoposition:terrainheight { //Should compare current orbit periapsis to the ship's current distance above ground level (NOT "sea" level)
        lock throttle to 1.
    }
    lock throttle to 0.
}

function distanceToGround {
    // Distance to Ground: altitude - body:geopositionOf(ship:position):terrainHeight - distance from center of craft to bottom.
    return altitude - body:geopositionOf(ship:position):terrainHeight - 10. //Constant at the end is supposed to account for the distance between the CoM of the craft and the bottom
}
function stoppingDistance {
    // Stopping Distance: v^2 / 2a, a = ship thrust / ship mass - a due to local body gravity (G*M / R^2)
    local gravity is constant():g*(body:mass / body:radius^2).
    local maxAcceleration is (ship:availableThrust / ship:mass) - gravity.
    return (ship:groundspeed^2 + ship:verticalspeed^2) / (2 * maxAcceleration).
}
function executeLandingBurn {
    //We will need to calculate the correct altitude for a "suicide burn" 
    //Thrust of Engines: 60.69kN == 606900N
    //(altitude to start suicide burn) = [ (current altitude)(acceleration of gravity) + (1/2)(current velocity)2 ] / (acceleration of engines)
    //suicide_alt = (ship:altitude*1.63 + 0.5*(SHIP:VELOCITY:SURFACE)^2)/60690
    wait until altitude < 20000.
    lock steering to srfRetrograde.
    lock percentThrottle to stoppingDistance() / distanceToGround(). //Ratio of how far we need to stop over how far up we actually are. Throttle follows the change in this value.
    until (percentThrottle > 1){
        print "Percent Throttle: " + percentThrottle.
        print "Stopping Distance: " + stoppingDistance().
        print "Distance to ground: " + distanceToGround().
        wait 5.
    }
    lock throttle to percentThrottle.
    when distanceToGround() < 500 then { gear on. print "Landing Gear Deploying.".} //Deploy landing gear at 500m AGL
    wait until ship:verticalSpeed > 0. // Looking at our vertical speed relative to the ground, if > 0, we are starting to go up again.
    lock throttle to 0.
    unlock steering.
    wait 2.

    // wait until (ship:altitude-ship:geoposition:terrainheight < 8000).
    // local suicide_alt is ((ship:altitude-ship:geoposition:terrainheight)*1.63 + 0.5*(SHIP:VELOCITY:SURFACE:sqrmagnitude))/60.690.
    // print "Ship Alt: " + ship:altitude.
    // print "Terrain height: " + ship:geoposition:terrainheight.
    // print "Alt - terrain height: " + (ship:altitude-ship:geoposition:terrainheight).
    // print "Suicide Alt: " + suicide_alt.
    // //print "Alt Radar: " + alt:radar.
    // wait until (ship:altitude-ship:geoposition:terrainheight <= (suicide_alt + 1000)).
    // //until(ship:altitude-ship:geoposition:terrainheight <= 10){
    //     set LANDINGPID to PIDLOOP(
    //     50,  // adjust throttle 0.1 per 5m in error from desired altitude.
    //     0.1, // adjust throttle 0.1 per second spent at 1m error in altitude.
    //     30,  // adjust throttle 0.1 per 3 m/s speed toward desired altitude.
    //     0,   // min possible throttle is zero.
    //     1    // max possible throttle is one.
    // ).
    // set LANDINGPID:SETPOINT to 5.
    // until false {
    //     set mythrot to LANDINGPID:UPDATE(TIME:SECONDS, alt:radar).
    //     wait 0.5.
    //     print "Alt Radar: " + alt:radar.
    //     print "Throttle: " + mythrot.
    //     lock throttle to mythrot.
    // }
    }
    //ship:geoposition:terrainheight gives height of terrain above sea-level at the ship's current position.
    //ship:altitude gives height of the ship above sea level.
    
    //Things we need to know: Current altitude, current relative surface velocity, delta v required to safely land, how long the burn will be to scrub off excess speed.
    //PID loops would probably be useful here for attitude and altitude control.
    // Throttle up when below target altitude, throttle down when above
    //EXAMPLE PID from KOS docs:
// target altitude, trying to hover:
// local target_alt is 100.
// set HOVERPID to PIDLOOP(
//     50,  // adjust throttle 0.1 per 5m in error from desired altitude.
//     0.1, // adjust throttle 0.1 per second spent at 1m error in altitude.
//     30,  // adjust throttle 0.1 per 3 m/s speed toward desired altitude.
//     0,   // min possible throttle is zero.
//     1    // max possible throttle is one.
//   ).
// set HOVERPID:SETPOINT to target_alt.
// set mythrot to 0.
// lock throttle to mythrot.
// until false {
//   set mythrot to HOVERPID:UPDATE(TIME:SECONDS, alt:radar).
//   wait 0.
// }

function executeRoverInsertion {
    //PID loop to hover above a certain "safe" altitude to deploy the rover.
    //Should be simple stage instructions to detach rover. Might want to think about safety checks in the future to make sure it is actually a viable landing location.
    stage.
    wait 1.
    lock throttle to 0.5.
    wait 3.
    lock throttle to 0.

}
main().