//Script to automate landing of the Vacuum Delivery System (VDS) on any celestial body.
//FEATURES TO IMPLEMENT: 
//  -Surface slope detection and compensation (figure out if the place we're landing is hella sloped and adjust trajectory)
//  -Slop stabliization (if we've landed on a slope that's slightly tilted, compensate with steering adjustments to make a stable landing)
//  -Hover PID for rover insertion
function main {
    //createLandingTrajectory(). //Function to calculate a (hopefully) desirable trajectory for landing.
    deOrbit(). //Function to de-orbit the VDS to initiate the landing sequence.
    executeLandingBurn(). //Function to execute the required landing burn.
    executeRoverInsertion(). //Function to safely detach rover from VDS.
    print "P63 completed.".
}
function createLandingTrajectory { //One day I will add capability to land at a specific location/biome.
     
}
function executeLandingTrajectory { //Executes manuever node generated by createLandingTrajectory().

}
//This function will create a trajectory intersecting with the surface of the body
function deOrbit {
    stage.
    lock steering to retrograde.
    wait 20.
    //Takes VDS from stable orbit to suborbital landing trajectory
    //Things we need to know: Periapsis of current orbit (how do we know if the periapsis is low enough? maybe there are parameters for "sea" level vs ground level)
    //is there a way to ensre we are landing somewhere safe? (future integration of SCANSAT slope data possible?)
    local deorbit_alt is (ship:geoposition:terrainheight).
    print "Terrain Height below current ship position: " + deorbit_alt.
    print "Distance to ground at current ship position: " + distanceToground().
    until periapsis <= ship:geoposition:terrainheight { //Should compare current orbit periapsis to the ship's current distance above ground level (NOT "sea" level)
        lock throttle to 1.
    }
    lock throttle to 0.
}
//This function finds the distance above the terrain the ship currently is
function distanceToGround {
    // Distance to Ground: altitude - body:geopositionOf(ship:position):terrainHeight - distance from center of craft to bottom.
    return altitude - body:geopositionOf(ship:position):terrainHeight - 10. //Constant at the end is supposed to account for the distance between the CoM of the craft and the bottom
}

//Function to return the rate of change of altitude with a delta t == 0.1
function deltaDTG {
    // Position Rate of Change
    local x1 is altitude - body:geopositionOf(ship:position):terrainHeight.
    wait 0.1.
    local x2 is altitude - body:geopositionOf(ship:position):terrainHeight.
    //print "Delta X: " + (x2-x1).
    return x2-x1.
}
//This function calculates the distance needed to burn off all our velocity
function stoppingDistance {
    // Stopping Distance: v^2 / 2a, a = ship thrust / ship mass - a due to local body gravity (G*M / R^2)
    local gravity is constant():g*(body:mass / body:radius^2).
    local maxAcceleration is (ship:availableThrust / ship:mass) - gravity.
    return (ship:groundspeed^2 + ship:verticalspeed^2) / (2 * maxAcceleration).
}
function executeLandingBurn {
    //We will need to calculate the correct altitude for a "suicide burn" 
    //Thrust of Engines: 60.69kN == 606900N
    //(altitude to start suicide burn) = [ (current altitude)(acceleration of gravity) + (1/2)(current velocity)2 ] / (acceleration of engines)
    //suicide_alt = (ship:altitude*1.63 + 0.5*(SHIP:VELOCITY:SURFACE)^2)/60690
    wait until altitude < 20000.
    local roverinsert is false.
    lock steering to srfRetrograde.
    lock percentThrottle to stoppingDistance() / distanceToGround(). //Ratio of how far we need to stop over how far up we actually are. Throttle follows the change in this value.
    until (percentThrottle > 1){
        print "Percent Throttle: " + percentThrottle.
        print "Stopping Distance: " + stoppingDistance().
        print "Distance to ground: " + distanceToGround().
        wait 5.
    }
    lock throttle to percentThrottle.
    until (roverinsert){
        when distanceToGround() < 500 then {gear on.} //Deploy landing gear at 500m AGL
        when distanceToGround() < 100 then {
            beginHover(20). 
            set roverinsert to true.}
    }
}
//This function uses an elementary PID to hover at a certain altitude so we can safely insert our rover (in theory)
function beginHover {
    //local setpoint is stoppingDistance() / distanceToGround() + 0.2. //Set our initial setpoint to a slightly more aggressive throttle to 
    parameter targetAltitude.
    local setpoint is 0.314. //Calculated value using kinematics to determine what % of throttle is needed to reach a V-speed of < 5 m/s between 100m AGL and our target altitude.
    lock throttle to setpoint.
    wait until ship:verticalspeed > -5.
    local valueModifier is constant():g*(body:mass * ship:mass / body:radius^2) / 9.81. //Modify our relative values based off the Fg ratios of the body we are trying to land on vs Kerbin (needs tweaking)
    local counter is 0.
    lock steering to up.
    //wait until distanceToGround() <= targetAltitude+5. // Plus 5 for safety
    until (counter > 10)
    {
        print "Throttle: " + setpoint.
        if(deltaDTG < -0.1 and distanceToGround() < targetAltitude){set setpoint to 0.55*valueModifier.} //Big thrust to neutralize large negative velocities.
        if(deltaDTG > 0.1 and distanceToGround() > targetAltitude){set setpoint to 0.35*valueModifier.} 
        if deltaDTG() < 0{
            set setpoint to setpoint + 0.05*valueModifier.
        }
        if deltaDTG() > 0{
            set setpoint to setpoint - 0.05*valueModifier.
        }
        if (distanceToGround() < targetAltitude + 2 and distanceToGround() > targetAltitude - 2) {
            print "Counter: " + counter.
            set counter to counter + 1.
        }
        else{ //Reset our counter if stability constraints are not met
            set counter to 0.
        }
    }
    print "Stability for 10 ticks achieved.".
}
function executeRoverInsertion {
    //PID loop to hover above a certain "safe" altitude to deploy the rover.
    //Should be simple stage instructions to detach rover. Might want to think about safety checks in the future to make sure it is actually a viable landing location.
    stage.
    wait 1.
    lock steering to up.
    lock throttle to 0.5.
    wait 3.
    lock throttle to 0.

}
main().
